{
    "name": "OdooIndex Connector",
    "version": "19.0.1.0.0",
    "category": "Tools",
    "summary": "Sync installed modules and migration readiness with OdooIndex",
    "author": "Daniel Reis,OdooIndex.com",
    "website": "https://github.com/OdooEssentials/odooindex_connector",
    "license": "LGPL-3",
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "views/res_config_settings_views.xml",
        "wizards/odooindex_connector_pair_wizard_views.xml",
        "views/ir_module_module_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
